worker_processes 1;
pid /var/run/nginx.pid;

events {
    worker_connections 128;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log off;
    error_log /dev/stderr warn;
    sendfile on;
    keepalive_timeout 15;

    server {
        listen 8080;
        server_name _;
        root /usr/share/nginx/html;

        location / {
            limit_except GET HEAD {
                deny all;
            }
            add_header Cache-Control "public, max-age=300";
            try_files $uri =404;
        }
    }
}
